name: lint
on: [push, pull_request]
jobs:
  lint:
    strategy:
      matrix:
        go-version: [1.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout 3m --verbose
